name = "phonghocchothue-frontend"
compatibility_date = "2024-05-09"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_URL_API = "https://api-phct-1.chickenkiller.com/"
