/**
 * Vietnamese Text & HTML Orthography Normalizer
 * 
 * 1. Unicode Normalization:
 *    Converts all Decomposed Unicode (NFD / Tổ hợp) generated by macOS, iOS, Safari
 *    into Precomposed Unicode (NFC / Dựng sẵn) supported by custom fonts.
 * 
 * 2. Tone Placement Normalization (Quy tắc đặt dấu thanh):
 *    In Vietnamese phonology, open syllables ending in diphthongs (oa, oe, uy without coda)
 *    differ between Old Style (Dấu kiểu cũ trên Mac/iOS: hoạ, toà, khoẻ, thuỷ) and
 *    New Style (Dấu kiểu mới trên Windows/Font chuẩn: họa, tòa, khỏe, thủy).
 *    This utility normalizes 100% of these phonetic cases while preserving:
 *    - Onset 'qu' words (quý, quỳ, quỷ, quỹ, quỵ)
 *    - Closed syllables with coda (hoàn, toán, khoán, loạn, hoặc, chuột, luyện...)
 *    - Triphthongs (ngoài, xoay, khuấy, khuyên, duyệt, khuỷu...)
 *    - All case variants (lowercase, TitleCase, ALL CAPS).
 */

const MAP_OA_LOWER: Record<string, string> = {
  'à': 'òa', 'á': 'óa', 'ả': 'ỏa', 'ã': 'õa', 'ạ': 'ọa'
};
const MAP_OA_UPPER: Record<string, string> = {
  'À': 'Òa', 'Á': 'Óa', 'Ả': 'Ỏa', 'Ã': 'Õa', 'Ạ': 'Ọa'
};
const MAP_OA_ALL_CAPS: Record<string, string> = {
  'À': 'ÒA', 'Á': 'ÓA', 'Ả': 'ỎA', 'Ã': 'ÕA', 'Ạ': 'ỌA'
};

const MAP_OE_LOWER: Record<string, string> = {
  'è': 'òe', 'é': 'óe', 'ẻ': 'ỏe', 'ẽ': 'õe', 'ẹ': 'ọe'
};
const MAP_OE_UPPER: Record<string, string> = {
  'È': 'Òe', 'É': 'Óe', 'Ẻ': 'Ỏe', 'Ẽ': 'Õe', 'Ẹ': 'Ọe'
};
const MAP_OE_ALL_CAPS: Record<string, string> = {
  'È': 'ÒE', 'É': 'ÓE', 'Ẻ': 'ỎE', 'Ẽ': 'ÕE', 'Ẹ': 'ỌE'
};

const MAP_UY_LOWER: Record<string, string> = {
  'ỳ': 'ùy', 'ý': 'úy', 'ỷ': 'ủy', 'ỹ': 'ũy', 'ỵ': 'ụy'
};
const MAP_UY_UPPER: Record<string, string> = {
  'Ỳ': 'Ùy', 'Ý': 'Úy', 'Ỷ': 'Ủy', 'Ỹ': 'Ũy', 'Ỵ': 'Ụy'
};
const MAP_UY_ALL_CAPS: Record<string, string> = {
  'Ỳ': 'ÙY', 'Ý': 'ÚY', 'Ỷ': 'ỦY', 'Ỹ': 'ŨY', 'Ỵ': 'ỤY'
};

const VN_WORD_REGEX = /[a-zA-ZàáảãạăắằẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵđĐ]+/g;

export function normalizeVietnameseWord(word: string): string {
  if (!word || typeof word !== 'string') return word;
  let res = word.normalize('NFC');

  // 'qu' onset: 'quý, quỳ, quỷ, quỹ, quỵ' have main vowel 'y', so tone stays on 'y'
  if (/^qu[yýỳỷỹỵ]/i.test(res)) {
    return res;
  }

  // 1. Open syllables ending with 'oa' (e.g. hoạ -> họa, toà -> tòa, xoá -> xóa)
  res = res.replace(/^([a-zA-ZàáảãạăắằẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵđĐ]*?)o([àáảãạÀÁẢÃẠ])$/, (_match, prefix, toneA) => {
    const isAllCaps = toneA === toneA.toUpperCase() && (prefix === prefix.toUpperCase() || prefix.length === 0);
    const isTitle = toneA === toneA.toUpperCase() && !isAllCaps;
    const map = isAllCaps ? MAP_OA_ALL_CAPS : (isTitle ? MAP_OA_UPPER : MAP_OA_LOWER);
    return prefix + (map[toneA] || ('o' + toneA));
  });

  // 2. Open syllables ending with 'oe' (e.g. khoẻ -> khỏe, loé -> lóe, xoè -> xòe)
  res = res.replace(/^([a-zA-ZàáảãạăắằẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵđĐ]*?)o([èéẻẽẹÈÉẺẼẸ])$/, (_match, prefix, toneE) => {
    const isAllCaps = toneE === toneE.toUpperCase() && (prefix === prefix.toUpperCase() || prefix.length === 0);
    const isTitle = toneE === toneE.toUpperCase() && !isAllCaps;
    const map = isAllCaps ? MAP_OE_ALL_CAPS : (isTitle ? MAP_OE_UPPER : MAP_OE_LOWER);
    return prefix + (map[toneE] || ('o' + toneE));
  });

  // 3. Open syllables ending with 'uy' (e.g. thuỷ -> thủy, thuý -> thúy, luỹ -> lũy)
  res = res.replace(/^([a-zA-ZàáảãạăắằẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵđĐ]*?)u([ỳýỷỹỵỲÝỶỸỴ])$/, (_match, prefix, toneY) => {
    if (/^qu/i.test(prefix + 'u')) return _match;
    const isAllCaps = toneY === toneY.toUpperCase() && (prefix === prefix.toUpperCase() || prefix.length === 0);
    const isTitle = toneY === toneY.toUpperCase() && !isAllCaps;
    const map = isAllCaps ? MAP_UY_ALL_CAPS : (isTitle ? MAP_UY_UPPER : MAP_UY_LOWER);
    return prefix + (map[toneY] || ('u' + toneY));
  });

  return res;
}

export function normalizeVietnameseText(text: string): string {
  if (!text || typeof text !== 'string') return text;
  let res = text.normalize('NFC');
  return res.replace(VN_WORD_REGEX, (w) => normalizeVietnameseWord(w));
}

export function normalizeVietnameseHtml(html: string): string {
  if (!html || typeof html !== 'string') return html;
  let res = html.normalize('NFC');
  return res.replace(/(^|>)([^<]+)(<|$)/g, (_match, prefix, text, suffix) => {
    return prefix + normalizeVietnameseText(text) + suffix;
  });
}

export default normalizeVietnameseHtml;
